name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn publish
        if: github.event == 'push'
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@chantouch'
      - run: yarn publish
        if: github.event == 'push'
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
